# Generated by Django 4.2 on 2023-05-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='district',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='materials',
        ),
        migrations.AlterField(
            model_name='bank',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='dob',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
