# Generated by Django 4.2 on 2023-05-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_remove_bank_account_remove_bank_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
